### ISSUE TITLE
Configuration/Setup Query

### ISSUE THREAD

**Issue by NeilRenwick** [mehrgithub/dcrmeg#30]
Hi,

I had a general question which I can't find reference to in the documentation and wondered if it's possible to achieve. I require 4 grids on the same form which all display data from the same entity. I've set this up in a test environment and created four seperate configurations so each web resource on the form has a different GUID. I hoped this would mean the records displayed in each grid would be specific to each configuration but when creating a new record in any of the grids it is added to all four of them. Is there a method of configuring so that the records added are unique to each grid? I'm currently on version 1.0.6.0 but can upgrade to a new version if necessary.

Thanks in advance

**Comment by mehrgithub** [comment]
Hi,

One way to achieve the functionality is to use field level filters. Similar to what you may use to display different sets of data from the same entity in a CRM view.

For example:
You have a field "Fieldx (optionset/numeric/date/lookup/...)" that can be used as a filter to display different sets of data from the same entity.

Assuming Fieldx is an optionset:

- In Grid One, set a filter for Fieldx to display records matching option3. Set Fieldx "Create new, default value top Option3.
- In Grid Two, set a filter for Fieldx to display records matching option2. Set Fieldx "Create new, default value top Option2.
- In Grid Three, set a filter for Fieldx to display records matching option4. Set Fieldx "Create new, default value top Option4.
- In Grid Four, set a filter for Fieldx to display records matching option6. Set Fieldx "Create new, default value top Option6.

Now each grid will display a different set of data from the same entity based on the filter.

To handle creating new records, in the grid configuration for each Grid, you will need to set the default value for the Fieldx under "Create new, default value", as mentioned in the example above. Now, when you add a new record to any of the Grids, the value of Fieldx's "Create new, default value" for that specific Grid will be used. This will ensure the new record will only be displayed on that Grid where the record was added. This step can also be done using a work flow that sets the Fieldx value of a new record to a specific value based on your requirements.

Although you don't need to upgrade to the latest version to achieve the functionality you have described, I would recommend upgrading to the latest version as there has been many bug fixes and improvements since v1.0.6.0.

If this answered your question, please mark it as closed.

Thank you,
Mehrdad

**Comment by NeilRenwick** [comment]
Hi Mehrdad,

Thank you for your quick response. The option you have suggested does work but unless I am mistaken there is no method of pre-selecting the filter in the configuration, the filter can only be applied on the grid. This means every time a new record is created for the entity form on which the grids are displayed, they would need to set the filters on each of the four grids in order to filter out the records they do not wish to see. Is there any method of pre-setting filters and if not is this additional functionality that could be added? 

Thanks as always

**Comment by mehrgithub** [comment]
Hi Neil,

You can preset filters from the Grid configuration. And you aren't limited to only the fields on the grid. Please see the following documentation page:

Field Conditions: https://github.com/mehrgithub/dcrmeg/blob/master/docs/Field%20Conditions.md

Thank you,
Mehrdad

**Comment by NeilRenwick** [comment]
Amazing, thanks so much. I didn't even realise that setting was there. Fantastic work on this truly incredible grid.
