### ISSUE TITLE
Dynamics 365

### ISSUE THREAD

**Issue by acraigx** [mehrgithub/dcrmeg#8]
Any issues with using this with Dynamics 365?  If so, are you planning to release a compatible version?

**Comment by mehrgithub** [comment]
There is one issue, the grid is using Organization Data Service (soap end points) via XrmServiceToolkit library. As you may know, Organization Data Service is deprecated.

I was planning to replace the XrmServiceToolkit with a WebAPi based library, However, since Dynamics 365 comes with an editable grid, I decided not to invest the time.

Thank you,
Mehrdad

**Comment by acraigx** [comment]
I went back to my users and they would truly appreciate if you could upgrade your solution.  They love the look, feel and ease of use of your grids.  If this is possible you’ll make a bunch of people very happy ☺

Thanks!
Craig

**Comment by mehrgithub** [comment]
Started replacing Organization Data Service with WebApi. However, I can't give you an estimate as there are many instances that need to be changed and adjusted. Example, in the main grid, I need to change 53 instances of soap calls alone.

Thank you,
Mehrdad

**Comment by acraigx** [comment]
Thank you thank you thank you!

**Comment by acraigx** [comment]
Hi again

I don’t want to rush you but am anxious to implement the changes for my users.  They do love this feature and after I showed them the standard Microsoft editable grid they cringed…  they prefer yours 100%!

Many thanks again
Craig

**Comment by mehrgithub** [comment]
Hi Craig,

Please download the new version and let me know if the new functionality is working properly.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad

**Comment by acraigx** [comment]
Thanks greatly!  Will do.
